apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-produto-configmap
  namespace: backend-estabelecimento
data:
  db_url: jdbc:postgresql://estabelecimento.cpmueqg0y0dn.us-east-1.rds.amazonaws.com:5432/estabelecimento
  db_username: "postgres"
  db_password: "12345678"
  redis_url: redis-estabelecimento.z1mqaz.0001.use1.cache.amazonaws.com