apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-produto-configmap
  namespace: backend-estabelecimento
data:
  db_url: jdbc:postgresql://produto.cf4grgsaa5x0.us-east-1.rds.amazonaws.com:5432/produto
  db_username: "postgres"
  db_password: "12345678"
  redis_url: redis-produto.b0jn9d.0001.use1.cache.amazonaws.com