apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-estabelecimento-hpa
  namespace: backend-estabelecimento
  labels:
    app.kubernetes.io/name: backend-estabelecimento
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-estabelecimento-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65