apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::975049952960:role/LabRole
  name: backend-produto-serviceaccount
  namespace: backend-estabelecimento