apiVersion: v1
kind: Service
metadata:
  name: backend-produto-svc
  namespace: backend-estabelecimento
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "backend-produto-svc"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/actuator/health"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: backend-produto-app