@startuml Clean Architecture
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(estabelecimento, "Estabelecimento", "Pessoa que gerencia o estabelecimento")

System_Boundary(cadastraProduto, "Cadastra Produto") {
    Component(produtoApi, "ProdutoApi", "API", "Recebe requisições HTTP e delega para o controller")
    Component(produtoController, "ProdutoController", "Controller", "Recebe requisições e delega para o caso de uso")
    Component(cadastraProdutoUseCase, "CadastraProdutoUseCase", "Caso de Uso", "Contém a lógica de negócio para cadastro de produto")
    Component(produto, Produto, "Entidade", "Modelos de domínio")
    Component(cadastraProdutoGateway, "CadastraProdutoGateway", "Gateway", "Acesso a inteface de comunicação externa")
    Component(produtoRepository, "ProdutoRepository", "Repositório", "Acesso a dados e persistência")
    ComponentDb(clienteDb, "Cliente DB", "Banco de Dados", "Banco de Dados com informações de Produto")

    Rel(estabelecimento, produtoApi, "Usa", "HTTP POST /api/v1/produtos")
    Rel(produtoApi, produtoController, "Chama", "Método")
    Rel(produtoController, cadastraProdutoUseCase, "Usa", "Interface de Caso de Uso")
    Rel(cadastraProdutoUseCase, produto, "Manipula", "Objeto de Domínio")
    Rel(cadastraProdutoUseCase, cadastraProdutoGateway, "Usa", "Interface de Repositório")
    Rel(cadastraProdutoGateway, produtoRepository, "Usa", "Interface de Repositório")
    Rel(produtoRepository, clienteDb, "Usa", "Spring Data")
}

SHOW_LEGEND()
@enduml