@startuml Clean Architecture
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(Cliente, "Cliente", "Pessoa que pretende acompanhar pedido")

System_Boundary(listaProdutos, "Listar Produtos") {
    Component(produtoApi, "ProdutoApi", "API", "Recebe requisições HTTP e delega para o controller")
    Component(produtoController, "ProdutoController", "Controller", "Recebe requisições e delega para o caso de uso")
    Component(listaProdutosUseCase, ListaProdutosUseCase, "Caso de Uso", "Contém a lógica de negócio para listagem de produtos")
    Component(produto, Produto, "Entidade", "Modelos de domínio")
    Component(ListaProdutosGateway, "ListaProdutosGateway", "Gateway", "Acesso a inteface de comunicação externa")
    Component(produtoRepository, "ProdutoRepository", "Repositório", "Acesso a dados e persistência")
    ComponentDb(produtoDb, "Produto DB", "Banco de Dados", "Banco de Dados com informações de Produtos")

    Rel(Cliente, produtoApi, "Usa", "HTTP GET /api/v1/produtos")
    Rel(Cliente, produtoApi, "Usa", "HTTP GET /api/v1/produtos/lanches")
    Rel(Cliente, produtoApi, "Usa", "HTTP GET /api/v1/produtos/acompanhamentos")
    Rel(Cliente, produtoApi, "Usa", "HTTP GET /api/v1/produtos/bebidas")
    Rel(Cliente, produtoApi, "Usa", "HTTP GET /api/v1/produtos/sobremesas")
    Rel(produtoApi, produtoController, "Chama", "Método")
    Rel(produtoController, listaProdutosUseCase, "Usa", "Interface de Caso de Uso")
    Rel(listaProdutosUseCase, produto, "Manipula", "Objeto de Domínio")
    Rel(listaProdutosUseCase, ListaProdutosGateway, "Usa", "Interface de Repositório")
    Rel(ListaProdutosGateway, produtoRepository, "Usa", "Interface de Repositório")
    Rel(produtoRepository, produtoDb, "Usa", "Spring Data")
}

SHOW_LEGEND()
@enduml