name: 1 - [FEAT] Execute Tests and Open PR

on:
  push:
    branches:
      - "feature**"

jobs:
  create_pr_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Tests
        run: mvn -B test
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_title: "feat: Feature para Develop"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          pr_draft: true