name: 3 - [MAIN] Apply, Build & Deploy

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.6'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Update kube config
        run: aws eks update-kubeconfig --region us-east-1 --name tech-fiap-app
      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fiap-estabelecimento
          IMAGE_TAG: latest
        run: |
          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" deployment/k8s/deployment.yml && \
          kubectl apply -f ./deployment/k8s/namespace.yml 
          kubectl apply -f ./deployment/k8s/configmap.yml
          kubectl apply -f ./deployment/k8s/serviceaccount.yml
          kubectl apply -f ./deployment/k8s/deployment.yml
          kubectl apply -f ./deployment/k8s/service.yml
          kubectl apply -f ./deployment/k8s/hpa.yml
          kubectl apply -f ./deployment/k8s/ingress.yml